name: rat race
favicon: null
layout_spectrum: 0.8402603599242866
typography_spectrum: 0.8666957844980061
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.5429636205080897
  lightness: 0.689891085261479
  saturation: 0.6924692406319082
  rhythmicContrast: 0.22748576756566763
purpose: []
